import React, { useEffect, useState } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import { ShieldCheck, TrendingUp, TrendingDown, Minus, Clock, ArrowRight, Loader2 } from 'lucide-react';

const REG_COLORS = {
  GDPR: 'bg-blue-100 text-blue-800',
  HIPAA: 'bg-red-100 text-red-800',
  SOC2: 'bg-purple-100 text-purple-800',
  ISO27001: 'bg-green-100 text-green-800',
  DPDP: 'bg-orange-100 text-orange-800'
};

function ScoreBadge({ score }) {
  const color = score >= 70 ? 'text-green-600' : score >= 40 ? 'text-yellow-600' : 'text-red-600';
  return <span className={`text-xl font-bold ${color}`}>{score}</span>;
}

export default function History() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');

  useEffect(() => {
    axios.get('/api/reports')
      .then(r => setReports(r.data))
      .catch(() => setError('Could not load report history'))
      .finally(() => setLoading(false));
  }, []);

  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="bg-gray-900 px-6 py-4 flex items-center gap-3">
        <Link to="/" className="flex items-center gap-3">
          <div className="w-8 h-8 bg-indigo-600 rounded-lg flex items-center justify-center">
            <ShieldCheck size={18} className="text-white" />
          </div>
          <span className="text-white font-semibold text-lg">RegulaAI</span>
        </Link>
        <span className="text-gray-500 mx-2">/</span>
        <span className="text-gray-300 text-sm">Audit History</span>
      </header>

      <div className="max-w-4xl mx-auto px-6 py-8">
        <div className="flex items-center justify-between mb-6">
          <div>
            <h1 className="text-xl font-semibold text-gray-900">Audit History</h1>
            <p className="text-sm text-gray-500 mt-0.5">All compliance reports generated by your team</p>
          </div>
          <Link to="/"
            className="flex items-center gap-2 bg-indigo-600 hover:bg-indigo-700 text-white text-sm font-medium px-4 py-2 rounded-xl transition-all">
            + New Analysis
          </Link>
        </div>

        {loading && (
          <div className="flex items-center justify-center py-16">
            <Loader2 size={28} className="animate-spin text-indigo-600" />
          </div>
        )}

        {error && (
          <div className="bg-red-50 border border-red-200 text-red-700 text-sm p-4 rounded-xl">{error}</div>
        )}

        {!loading && !error && reports.length === 0 && (
          <div className="text-center py-20 text-gray-400">
            <ShieldCheck size={40} className="mx-auto mb-3 text-gray-300" />
            <p className="font-medium text-gray-500">No reports yet</p>
            <p className="text-sm mt-1">Run your first compliance analysis to see it here.</p>
            <Link to="/" className="mt-4 inline-block text-indigo-600 text-sm hover:underline">Run analysis →</Link>
          </div>
        )}

        {!loading && reports.length > 0 && (
          <div className="flex flex-col gap-3">
            {reports.map(r => (
              <Link key={r.reportId} to={`/report/${r.reportId}`}
                className="bg-white border border-gray-200 rounded-xl p-4 flex items-center gap-4 hover:border-indigo-300 hover:shadow-sm transition-all group">
                <div className="text-center min-w-16">
                  <ScoreBadge score={r.overallScore} />
                  <div className="text-xs text-gray-400 mt-0.5">score</div>
                </div>
                <div className="w-px h-10 bg-gray-100" />
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${REG_COLORS[r.regulation] || 'bg-gray-100 text-gray-600'}`}>
                      {r.regulation}
                    </span>
                  </div>
                  <div className="flex items-center gap-1 text-xs text-gray-400">
                    <Clock size={11} />
                    {new Date(r.generatedAt).toLocaleDateString('en-IN', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' })}
                  </div>
                </div>
                <ArrowRight size={16} className="text-gray-300 group-hover:text-indigo-500 transition-colors" />
              </Link>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}
